### PR TITLE
Refactor frontend for off-chain communication. Many bugs fixed

### LINKED ISSUE #152: Frontend: When opening an ongoing game after first visiting a ended game, the board is not displayed.
Steps to reproduce:
- Start and join two games
- End one of the games (e.g. by surrendering)
- Reload browser tab
- Visit ended game. It correctly shows the winner and no board
- Visit ongoing game. It does not show the board

Expected:
- Ongoing game shows board

### LINKED ISSUE #205: Refactor chess.js to gameFactory
# Task
## Detailed Description
- keep chessboard state in game object (of gamesFactory)
- move events from playGame.js to gamesFactory.js
- outsource utility functions
## Associated story

Story: #122

### LINKED ISSUE #210: Blockchain function to validate move by other player
# Task
## Detailed Description

Provide a function in Chess.sol that validates a move send by the not turning player.

If white has to turn and black claims timeout and uses `claimTimeoutEndedWithMove`, this function will be called by black.

### PR DESCRIPTION
**Pull request by graup**
- Utility functions (generate state and fen) outsourced into utils file
- Moved chess.js state to game state. Closes #205
- Use chess.js npm package instead of directly including code of library
- Moved event handling from playGame to gamesFactory
- Added last move time to localstorage to redisplay timeout after reload
- Show move number in UI
- Keep track of currently visible game (to enable notifications of moves in other games)
- Fixes #152
- Some other small bugs
- close #210

### CODE REVIEW

**Comment by kyroy** [comment]
```
WARNING in ./app/javascript/gamesFactory.js
jshint results in errors
  Line is too long. @ line 475 char 103
        console.log("Sent move no", game.state[8] * 128 + game.state[9], 'from', fromIndex, 'to', toIndex);

  Strings must use singlequote. @ line 475 char 31
        console.log("Sent move no", game.state[8] * 128 + game.state[9], 'from', fromIndex, 'to', toIndex);

  Line is too long. @ line 844 char 101
        if ((game.chess.turn() === 'w' && game.self.color === 'white' && data.args.timeoutState !== 0) ||

  Line is too long. @ line 845 char 101
            (game.chess.turn() === 'b' && game.self.color === 'black' && data.args.timeoutState !== 0)) {

  'generateState' is defined but never used. @ line 3 char 9
    import {generateState, generateFen} from './utils/fen-conversion.js';

WARNING in ./app/javascript/playGame.js
jshint results in errors
  Line is too long. @ line 173 char 112
            gameStates.addSelfMove(game.gameId, algebraicToIndex(move.from), algebraicToIndex(move.to), game.state);
```

**Comment by graup** [comment]
There are some new bugs, but I wanted to get this PR up now because I won't have time to look at it further until tomorrow.

Sometimes I get an error that the move counts don't match after reloading. Also the notification for new moves in other games doesn't work 100% yet.

**Comment by kyroy** [comment]
Were these bugs also existing before he refactoring?

**Comment by graup** [comment]
Before refactoring lots of other things didn't work, so it wasn't really possible to see them. I would say these are new bugs. The basic move, claims / react to claim events and reading from local storage still works.

**Comment by kyroy** [comment]
~~`games.update` needs to be changed (see `games.add`)~~  => done

**Comment by kyroy** [comment]
```
let lastMoveTime;
try {
  // Try to find out time of last move
  lastMoveTime = gameStates.getLastMoveTime(game);
  if (!lastMoveTime) {
    // get it from blockchain?
  }
} catch (e) {
}
```

The last move time is not stored in the contract. However, we could search the transaction where the last move was made / when the game was joined by the second player

**Comment by kyroy** [comment]
When pressing surrender or close, the message "waiting..." is present, but does not get updated. When reloading the page, the action is already completed.

**Comment by kyroy** [comment]
At some point, we should also remove the move listeners ;)

File: app/javascript/gamesFactory.js [hunk 1]
```diff
@@ -189,16 +256,27 @@ angular.module('dappChess').factory('games', function (crypto, navigation, gameS
    */
   games.update = function (game) {
     console.log('update game called', game);
-    for(let i in games.list) {
-      if(games.list[i].gameId === game.gameId) {
-        games.list[i] = game;
+    for (let i in games.list) {
+      if (games.list[i].gameId === game.gameId) {
+        // update existing game
+        let g = games.list[i];
```
Comment (dennis-westphal) [inline app/javascript/gamesFactory.js]: I only used the for loop because I wasn't sure if arr.find would return a reference, but it does; so you can replace the whole loop by let g = games.getGame(game.gameId);

File: app/javascript/gamesFactory.js [hunk 2]
```diff
@@ -189,16 +256,27 @@ angular.module('dappChess').factory('games', function (crypto, navigation, gameS
...
+        for (let key in game) {
+          g[key] = game[key];
+        }
```
Comment (dennis-westphal) [inline app/javascript/gamesFactory.js]: use jQuery.extend(true, g, game) instead if you want a deep copy, or jQuery.extend(g, game) if you want to replace sub-objects

File: app/javascript/gamesFactory.js [hunk 3]
```diff
@@ -403,6 +484,8 @@ angular.module('dappChess').factory('games', function (crypto, navigation, gameS
       'topic': [shhTopic, game.gameId],
       'payload': payload
     });
+    console.log('Sent move no', game.state[8] * 128 + game.state[9],
+                'from', fromIndex, 'to', toIndex);
```
Comment (dennis-westphal) [inline app/javascript/gamesFactory.js:512]: If this is not required anymore, remove it

File: app/javascript/gamesFactory.js [hunk 4]
```diff
@@ -431,7 +513,7 @@ angular.module('dappChess').factory('games', function (crypto, navigation, gameS
           console.log('Could not send state and move to blockchain', e);
         }
       }
-    }, 10000);
+    }, 3000);
```
Comment (dennis-westphal) [inline app/javascript/gamesFactory.js]: Can you move this to a constant? I'd rather change this for production use later.

File: app/javascript/gamesFactory.js [hunk 5]
```diff
@@ -447,23 +529,37 @@ angular.module('dappChess').factory('games', function (crypto, navigation, gameS
...
 
+  /**
+   * Check if a random move is valid, throws if no valid moves are possible 
+   * 
+   * @param game
+   * @returns {*[from index in 0x88, to index in 0x88]}
+   */
+  games.getValidMove = function (game) {
+    console.log('get valid move for', game);
+    let move = game.chess.moves()[0];
```
Comment (dennis-westphal) [inline app/javascript/gamesFactory.js]: I'd rename this to moveFrom or something similar for more clarity

File: app/javascript/gamesFactory.js [hunk 6]
```diff
@@ -735,40 +831,84 @@ angular.module('dappChess').factory('games', function (crypto, navigation, gameS
...
+    }
+
+    $rootScope.$apply();
+
+    // Check own state to confirm or decline
+    if (data.args.timeoutState !== 0 && (
+        (game.chess.turn() === 'w' && game.self.color === 'white') ||
+        (game.chess.turn() === 'b' && game.self.color === 'black'))) {
+      if (
+          ([1, 2].indexOf(data.args.timeoutState) !== -1 && game.chess.in_checkmate()) || // jshint ignore:line
```
Comment (dennis-westphal) [inline app/javascript/gamesFactory.js:939]: Just for understanding: Why does this also apply to a timeout game status? Maybe you could also add this to the comments

File: app/javascript/gamesFactory.js [hunk 7]
```diff
@@ -735,40 +831,84 @@ angular.module('dappChess').factory('games', function (crypto, navigation, gameS
...
+            'Could not confirm your game against ' + game.opponent.username + ' ended',
+            'error', 'playgame-' + game.gameId);
+          console.log('error while trying to confirm the game ended after draw', e);
+        }
+      } else { // no valid endgame
+        try {
+          games.sendLastStateOrMoveToBlockchain(game);
+        } catch (e) {
+          $rootScope.$broadcast('message',
+            'Could not send move to blockchain to decline endgame',
```
Comment (dennis-westphal) [inline app/javascript/gamesFactory.js]: Please write "end game" instead of "endgame", since it has a different meaning

File: static/playGame.html [hunk 8]
```diff
@@ -15,7 +15,7 @@
 <div class="container" data-ng-show="!isOpenGame()">
   <div class="eight columns">
     <p data-ng-show="gameIsActive()">
-      You are in an ongoing chess game, the pot is at {{game.pot}}.
+      You are in an ongoing chess game, the pot is at {{game.pot}}. Move no {{halfMoveNumber}}.
```
Comment (dennis-westphal) [inline static/playGame.html]: Can we please rephrase this? That's not a proper sentence ;-)

**Comment by dennis-westphal** [comment]
When starting a new game, I get this:

screen shot 2016-07-12 at 15 38 09

Move no. NaN is not really ideal ;-)

**Comment by dennis-westphal** [comment]
Offering a draw does not work for both sides:

screen shot 2016-07-12 at 15 41 18

**Comment by dennis-westphal** [comment]
When a game is won, the claimEther button is displayed. This should not be the cause; the frontend should automatically claim the ether (worked before).

**Comment by kyroy** [comment]
> the frontend should automatically claim the ether (worked before).

Ye, this worked for onchain... not for offchain ;)

**Comment by dennis-westphal** [comment]
Now there seems to be a different problem:

screen shot 2016-07-12 at 19 17 26

**Comment by dennis-westphal** [comment]
Also, the Move no NaN issue still exists.

**Comment by kyroy** [comment]
Ye, i am working on some problems ;)  
Atm i don't care about the move number... don't know why this was added ;)

**Comment by graup** [comment]
I encountered cases were the move couldn't be saved because the move number wasn't correct. If that's fixed we can remove the counter again :)

**Comment by kyroy** [comment]
The move that was send, was send with the old state, not with the new state. This may have caused the error ;)

File: app/javascript/gamesFactory.js (hunk 6 above)
Comment (kyroy) [inline app/javascript/gamesFactory.js:939]: Added

File: app/javascript/utils/fen-conversion.js [hunk 9]
```diff
@@ -0,0 +1,251 @@
...
+  } else {
+    fen += ' -';
+  }
+
+  // set clock for halfmoves since last capture or pawn advance
+  // not implemented, so always 0
+  fen += ' 0 ';
+
+  // set fullmove number
+  let halfMoveCounter = state[8] << 7 + state[9];
```
Comment (kyroy) [inline app/javascript/utils/fen-conversion.js]: @graup: this new line instead of: `let halfMoveCounter = 128 * state[8] + state[9];` causes problems. Finally found this bug. Normally, we should not try to 'optimize' working functions while refactoring, since new introduced bugs are very hard to trace ;)

Comment (graup) [inline app/javascript/utils/fen-conversion.js]: Oh no, sorry. That function had another bug (adding En passant flag twice) which I fixed, but apparently then I introduced a new bug.
Maybe translating state to move counter should be its own utility function with a comment, then that mistake couldn't happen.

**Comment by graup** [comment]
Proxy communication seems to work (better than before).

The last big bug is that `moveFromState` goes out-of-gas. Still haven't found a good way to debug that :(

File: static/playGame.html [hunk 10]
```diff
@@ -15,22 +15,22 @@
...
     <p data-ng-show="gameIsActive()">
-      You are in an ongoing chess game, the pot is at {{game.pot}}.
+      You are in an ongoing chess game, the pot is at {{game.pot}} Ether.
     </p>
     <p data-ng-show="gameIsWon()">
       You have won this game.
-      <span data-ng-show="getGame().pot > 0">The pot of {{getGame().pot}} is being transferred to you.</span>
-      <span data-ng-hide="getGame().pot > 0">The pot was transferred to you.</span>
+      <span data-ng-show="getGame().pot > 0">The pot of {{getGame().pot}} Ether is being transferred to you.</span>
+      <span data-ng-hide="getGame().pot > 0">The pot of {{getGame().pot}} Ether was transferred to you.</span>
```
Comment (lisasi) [inline static/playGame.html]: I added the pot size here, so the users see it after the game has ended. But pot and wonEther are set to zero already, so this does not work. If someone has an idea on how to fix that, that would be nice. Otherwise I change it to the state before.

Comment (kyroy) [inline static/playGame.html]: You would have to store it in the contract. Or you need to get it from the old blocks/transactions.

**Comment by lisasi** [comment]
Oh, i always read "another" as "other". Weird. Of course you're right @dennis-westphal!

File: app/less/table.less [hunk 11]
```diff
@@ -9,6 +9,6 @@ tbody {
     background-color:rgba(0, 0, 0, 0.2);
   }
   tr.selected {
-    background-color:rgba(0, 30, 0, 0.8);
+    background-color:rgba(129, 212, 250, 0.8);
```
Comment (dennis-westphal) [inline app/less/table.less]: Does not improve visability but makes it worse - espacially since the link now is almost invisible. Has to be removed again.

File: static/playGame.html (hunk 10 above)
Comment (dennis-westphal) [inline static/playGame.html]: This is why it was not displayed at first...

**Comment by graup** [comment]
Merging to clean up Issues. Going to create a new issue for the remaining bug(s).
